### ISSUE TITLE
Your help with "data field headings" or column headings?

### ISSUE THREAD

**Issue by kateblanch** [american-art/aaa#1]
Hello @KarenWeiss ! I'm working on a cross-reference of all the data fields that  AAC folks are including in their data sets. This is a general, working document for reference only (nothing final / unchangeable). The MARC and EAD xml is a little tough to decipher...so I wondered if you had a list of column headings or field names you could share with me? This would help me keep the task of indexing data points simple.

Let me know your thoughts. Thanks!

**Comment by VladimirAlexiev** [comment]
In the current export (data-v3) there are no MARC/EAD. There are excels with columns, and a doc with explanations.
