### ISSUE TITLE
map GeneralFormat and SpecificFormat

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/aaa#10]
GeneralFormat and SpecificFormat are very useful classifications, please emit them.
There are 11 GeneralFormat  and 135 SpecificFormat. Since these are not mapped to AAT, make them out as a local 2-level thesaurus.

Take eg http://data.americanartcollaborative.org/page/aaa/object/1639
that should have type "Artworks" and subtype "cartoon (humorous image)".
@workergnome @azaroth42 do you agree with this mapping:
```ttl
<aaa/object/nnn>
  crm:P2_has_type
    <aaa/thesaurus/object/artworks>,
    <aaa/thesaurus/object/cartoon_humorous_image>.

<aaa/thesaurus/object/artworks> a skos:Concept;
  skos:inScheme <aaa/thesaurus/object/>;
  skos:prefLabel "Artworks".
  
<aaa/thesaurus/object/cartoon_humorous_image> a skos:Concept;
  skos:inScheme <aaa/thesaurus/object/>;
  skos:broader <aaa/thesaurus/object/artworks>;
  skos:prefLabel "cartoon (humorous image)".
```

**Comment by tobiashreiter** [comment]
@VladimirAlexiev , these have been mapped to AAT terms. We have extra spreadsheets in the data-v3 folder, one for general formats, and for specific formats, that links our local term to the AAT code and term.

**Comment by VladimirAlexiev** [comment]
- where are the sheets mapping GeneralFormat and SpecificFormat? I just pulled and I can't see them in 
- occupations are mapped to AAT in "AAA Role Term mapping-final.xlsx", I'll note this in https://github.com/american-art/aac_mappings/issues/65
- Item_DigitalResources.xls is not usable because the ids-internal.si.edu server is not visible on the internet, right?

**Comment by tobiashreiter** [comment]
- They're in data-v3: `AAA General Format Mapping To AAT.xlsx` and `AAA Specific Format Mapping To AAT.xlsx`.
- That's correct. Just as a note, the mapping there are split into three tabs. The first tab maps to AAT, the second tab maps to Library of Congress Subject Headings (LCSH)
- The Item_DigitalResources file was updated on May 15th to use our publicly facing URL. If you have an older version of the file, it might have the old URL.

**Comment by VladimirAlexiev** [comment]
Weirdness: I see them in https://github.com/american-art/aaa/tree/master/data-v3. But when I Pull or Fetch (or even Revert), I don't see them in my working directory.

Same for Item_DigitalResources.xls:
- on the web I see Commits on May 16, 2017: Changes for Nikhila  … Toby Reiter committed 2 days ago
- but locally I only see 5/5/2017 9:41:37 PM, Toby Reiter, Latest data export
Made a task to map them: https://github.com/american-art/aaa/issues/13

**Comment by VladimirAlexiev** [comment]
Of course, it's better to emit AAT concepts. I propose this changed mapping:
```ttl
<aaa/object/nnn> crm:P2_has_type aat:300133025, aat:300123430.

aat:300133025 a skos:Concept;
  skos:prefLabel "Artworks".
  
aat:300123430 a skos:Concept;
  skos:broader aat:300133025;
  skos:prefLabel "cartoon (humorous image)".
```

It would still be best to emit `skos:broader` according to AAA's 2-level classification. I've extracted it from objects (Item.xls) like this:
```
>csvcut -t -e cp1251 -c GeneralFormat,SpecificFormat Item.txt|sort|uniq -c>Item-Format.txt
```
[Item-Format.txt](https://github.com/american-art/aaa/files/1010270/Item-Format.txt)
@tobiashreiter can you add such column "parent" to `AAA Specific Format Mapping To AAT.xlsx`

**Comment by tobiashreiter** [comment]
@VladimirAlexiev , just to be very clear, are you simply asking that the general format be added to the specific format spreadsheet in the first column? If so, would you prefer our internal (AAA) vocabulary for general format, or the AAT term?

**Comment by tobiashreiter** [comment]
@VladimirAlexiev : I've added the general format (using our internal vocabulary) to the Specific Format Mapping sheet.

**Comment by VladimirAlexiev** [comment]
AAT is preferred for the extra col, but ISI can do that mapping

**Comment by tobiashreiter** [comment]
Great. And, as a reminder, that mapping is available in the General Formats spreadsheet.

**Comment by tobiashreiter** [comment]
Mapped, with local terms replaced with AAT terms (where available). Using AAT "document genre" for General Format, and "format" for Specific Format.
