### ISSUE TITLE
map Events

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/aaa#11]
AAA has Item_Events.xls that is then used in Item_Subjects.xls. 
That's useful info and the mapping is very simple (@workergnome please confirm):
```ttl
<event/238> a crm:E5_Event;
  rdfs:label "Tennessee Centennial and International Exposition (1897 : Nashville, Tenn.)".

<object/3916> crm:P62_depicts <event/238>.
```

**Comment by tobiashreiter** [comment]
We would love to see events added. Unlike people and institutions, these never have a carried out by property on the item entity, but instead are subjects, using a refers to property.

**Comment by VladimirAlexiev** [comment]
A few of them are also used in Item_Collections.FKCREATOREVENTID

**Comment by tobiashreiter** [comment]
Mapped.
