### ISSUE TITLE
Map Physical Characteristic

### ISSUE THREAD

**Issue by tobiashreiter** [american-art/aaa#14]
Our physical characteristic field is missing.  It's in the PhysicalCharacteristic column in Items.xls spreadsheet, and we want it to be mapped using p45_consists_of -> E57_Material. This was missing from the "cheatsheet" we sent you.

**Comment by tobiashreiter** [comment]
This is somewhere between blocker and enhancement.

**Comment by workergnome** [comment]
Would you mind breaking these into two issues?

**Comment by tobiashreiter** [comment]
This was added but was mapped as a linguistic object with AAT classification (http://vocab.getty.edu/aat/300010358). I could reopen this if we decide to make it more semantic.
