### ISSUE TITLE
collection URL is wrong

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/aaa#5]
@KarenWeiss 
Item_Collections.xls makes out collection URLs with dot, eg
http://www.aaa.si.edu/collections.esther-mccoy-papers-5502.
But the actual URL has a slash, eg
https://www.aaa.si.edu/collections/esther-mccoy-papers-5502

Collections are not being mapped yet, but now's a good time to fix this error

**Comment by tobiashreiter** [comment]
Vladimir -- this is a good find. Also, our URLs are technically https:// based now, so the code needs to be updated to reflect this as well.

**Comment by tobiashreiter** [comment]
@VladimirAlexiev -- This is now addressed in the latest push.
