### ISSUE TITLE
emit production date

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/aaa#6]
Currently objects have no production info, eg
http://data.americanartcollaborative.org/page/aaa/object/200/production
http://data.americanartcollaborative.org/page/aaa/object/12906/production
But at least a production date is present:
DisplayDate  DateBegin	DateEnd

**Comment by tobiashreiter** [comment]
This seems to be fixed in my version. Not sure why it wasn't working in the old version, as I believe the mapping is the same.
