### ISSUE TITLE
map fkCoCreatorPersonID, fkCoCreatorInstitutionID

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/aaa#8]
http://data.americanartcollaborative.org/aaa/object/12057/production
maps only person/11031.
But that record also has fkCoCreatorPersonID=343, and that should be mapped.
@workergnome @azaroth42: for the time being, I think the same way as the main fkCreatorPersonID?

Also take care of fkCoCreatorInstitutionID

**Comment by workergnome** [comment]
Agreed.

**Comment by tobiashreiter** [comment]
Mapped.
